server:
  port: ${PORT:9092}

logging:
  path: ${LLOC:/srv/ntraders/logs}
  file: ${logging.path}/${LFILE:user-details-service.log}
  level:
    root: ${LLVL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: health,info



spring:
  cloud:
    discovery:
      enabled: false
  profiles:
    active: ${PROFILE:local}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:mysql://localhost:3307/ntraders
    username: root
    password: admin

#hystrix.command.default.execution.timeout.enabled=false
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=11000
#ribbon.ConnectTimeout=10000
#ribbon.ReadTimeout=10000
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/n_traders
#spring.datasource.username=root
#spring.datasource.password=root

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:postgresql://localhost:5432/ntraders
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false