eureka:
  client:
    registry-fetch-interval-seconds: 30
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA:http://localhost:8761/eureka}
ribbon:
  eureka:
    enabled: true
  eager-load:
    enabled: true

spring:
  cloud:
    discovery:
      enabled: true